### ISSUE TITLE
Not able to telnet to fetpulser.local 2015.

### ISSUE THREAD

**Issue by AbidHussain70** [GordonAnderson/FETpulser#3]
I am getting following error while running command _telnet fetpulser.local 2015_

**telnet: could not resolve fetpulser.local/2015: Name or service not known**

I tried other examples and those work fine. Can you please point out the problem.

**Comment by GordonAnderson** [comment]
You will need to have Bonjour installed on your system to enable using the name vs the IP address.

Gordon Anderson, Chief Engineer
GAA Custom Electronics, LLC
www.GAACustom.com
gaa@owt.com

**Comment by AbidHussain70** [comment]
Thanks for reply.
I was able to telnet using IP address.
telnet 192.168.4.1 2015
